### ISSUE TITLE
Default CLI args

### ISSUE THREAD

**Issue by pdeschen** [kevinjqiu/cdbcli#60]
You might want to consider using sensible defaults for the cli args, where host would default to localhost, port to 5984, and leaving username password would connect to an "unsecured" instance.

**Comment by kevinjqiu** [comment]
Hi Pascal,

The default for host and port are `localhost` and `5984` already. Maybe I misunderstood your comment?

**Comment by pdeschen** [comment]
Ah sorry about that. I got confused with the traceback I got following a connection refuse. Maybe you could trap that error into a user friendly message?

Also, what if my instance do not require a username/password? For some reason cdbcli returns with a 

> Error connecting to the couchdb instance: (u'unauthorized', u'Name or password is incorrect.')

While I can use curl without any issue.

**Comment by kevinjqiu** [comment]
@pdeschen Ahh I see. What version of cdbcli are you using? I believe this issue was fixed in the latest 0.9 version.

**Comment by kevinjqiu** [comment]
Closing. If you do find this is still an issue, please re-open this ticket and provide steps to reproduce. Thanks!
